name: 'Close Pull Requests'
description: 'Close all repository pull requests and delete respective branches'
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'delete'  
  color: 'yellow'
