name: Misc tests
on: workflow_dispatch

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: commit-test

      - run: date +%s > test.txt

      - run: |
          git config --global user.name 'Test Case'
          git config --global user.email 'test-case@users.noreply.github.com'
          git add test.txt
          git commit -m "Test committer"
          git push
